name: scrollerdex
description: "Pokedex with scrolling effect"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.4.2
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  get_it: ^7.6.7
  hooks_riverpod: ^2.5.1
  riverpod: ^2.5.1
  shared_preferences: ^2.2.2
  stacked_services: ^1.5.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
